### ISSUE TITLE
Script doesnt run

### ISSUE THREAD

**Issue by jaime10a** [chadmed/asahi-audio#2]
Hey, I keep getting ValueError: embedded null byte when running mac-audio.sh.
Here is my output:
```
Press Enter to continue...
Installation directory already exists.
Session manager dir already exists.
This machine is a j313.

Before we continue, please ensure that you have set every speaker to
60 percent in alsamixer. Make sure the 'Amp Gain' sliders are set to
zero. Do not continue until this has been done.
Press Enter to continue...

Setting device profile to Pro Audio...
Traceback (most recent call last):
  File "/home/jaime/asahi-audio/install.py", line 72, in <module>
    main()
  File "/home/jaime/asahi-audio/install.py", line 63, in main
    set_dev_profile(machine)
  File "/home/jaime/asahi-audio/install.py", line 24, in set_dev_profile
    ret = copy2(f"conf/{system}/session.conf",
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 233, in copyfile
    if _samefile(src, dst):
  File "/usr/lib/python3.10/shutil.py", line 210, in _samefile
    return os.path.samefile(src, dst)
  File "/usr/lib/python3.10/genericpath.py", line 100, in samefile
    s1 = os.stat(f1)
ValueError: embedded null byte
```

What I did:
`git clone https://github.com/chadmed/asahi-audio`
`cd asahi-audio`
`alsamixer`
`sudo ./mac-audio.sh`

Im on python 3.10.3
pipewire
Compiled with libpipewire 0.3.48
Linked with libpipewire 0.3.48

Also, it would be great if you clarify what has to be done in alsamixer exactly.
Thank you

**Comment by chadmed** [comment]
as per the readme, the J313 is not yet supported. this error happens because there is no folder in the repo matching the j313 machine. i should probably add some error handling for this sort of thing.

with respect to alsamixer, it's pretty self explanatory. turn down the volume controls to 60, and any sliders named "amp gain" set to zero. not sure what needs to be clarified here

**Comment by jaime10a** [comment]
Okay sorry didnt see that.
I just dont have any sliders named "amp gain". Probably because its an M1air.
I just have a "Master" Slider and on the sound card "Jack ADC" and "Jack Mixer" sliders

**Comment by chadmed** [comment]
yeah im going to refactor this so that i can throw real error messages, its silly the way it currently works and is why this is really only ready for testers still
