### ISSUE TITLE
j313 support?

### ISSUE THREAD

**Issue by derzahla** [chadmed/asahi-audio#6]
I cloned the j314 config and  basically "s/j314/j313/g"'d it all.  ran the scripts.  i changed the status=disabled to 'okay' in my DTS file.  Audio devices now show up in pulse audio, but still no sound.  
Note: I had audio/speakers on this macbook working perfectly about 6 months ago just by modifying my dts. Not sure what happened but I'd love to have it back!

Any suggestions or tips?

**Comment by chadmed** [comment]
Well without looking at any logs or debug information, I can already tell you that `s/j314/j313/d` isn't going to work at all. The speaker array on that machine is _entirely_ different and you will break Pipewire by making it try to map six channels to an array in which there are four. There's a reason I don't support that machine here.

The actual problem here is probably going to be that you haven't set the speaker playback mux to secondary in alsamixer or installed the Asahi UCM2 files. Try doing both.

**Comment by derzahla** [comment]
Thanks for the reply.  I do have alsa-ucm-conf-asahi installed as well as a /etc/modprobe.d conf file with "options snd-soc-macaudio please_blow_up_my_speakers=1".  Based on what you just said, I take it no simple changes like removing the extra two (subwoofer?) channels from your 10-j314-sink.conf   etc,  would make it suitable for the j313 hardware?  

The problem is, if I remove /etc/pipewire/pipewire.conf.d/10-j313-sink.conf(derived from your j314 config) then I no longer have any output devices at all besides "dummy output".   I wish I could figure out what changed since my speakers were working just fine at one time with only the simple .dts file modification.  Any other ideas?  I can post whatever debug output may be helpful. However, feel free to close if j313 is too far outside of your intended scope

**Comment by chadmed** [comment]
The output of `asahi-diagnose` would be a good place to start.

**Comment by derzahla** [comment]
OK!  right this way: https://dpaste.com/HPE5HVGXA

**Comment by chadmed** [comment]
Nothing in there jumps out at me as being a kernel issue. The fact that you only get dummy outputs without the Pipewire
config actually suggests that the UCM conf is not being parsed correctly. Can you try moving the `macaudio` folder from `/usr/share/alsa/ucm2/conf.d/` and see if that makes some sinks appear?

**Comment by derzahla** [comment]
holy crap - speakers are working fine now, thank you!!!  so somehere along the line I mustve saw the package alsa-ucm-conf-asahi and thought 'yeh, i want this' and thats what ended up breaking my sound?   Seems j313 audio work more or less 'out of the box'  but most other models require special configs?

**Comment by chadmed** [comment]
IIRC the problem is with how Pipewire parses UCM files, not the files themselves. PulseAudio had the same issue at some point.

**Comment by rscaboyke** [comment]
Same for me and anyway I read that for macbook pro 14 2021 the safety deamon should work and on github is marked “if tou foolow these steps its safe. Only thing is not knowing hiw to enable speakers in device-treemvgCombassJean-Marie ***@***.******@***.***+32 485894441BE 0769.937.302IBAN BE58 3632 1574 1679Op 9 jun. 2023 om 14:59 heeft ToCodeABluejay ***@***.***> het volgende geschreven:﻿

i changed the status=disabled to 'okay' in my DTS file. Audio devices now show up in pulse audio, but still no sound.

Could you possibly share what DTS file you edited to enable audio? I would like to give it a try, and would be willing to spend some time on the configuration to get it, if not right, then at least usable and not particularly dangerous...I have re-configured the files in this repo in a similar way and have also installed 'alsa-ucm-conf-asahi', but I would really like to get working on this. I don't do anything that would require intensive use of speakers on high volume, nor do I need a perfectly mastered EQ, but merely having audio at all makes a huge difference in being able to use any setup for any extended period of time. Thank you very much!!
