### ISSUE TITLE
How can I change the pro audio pipewire profile?

### ISSUE THREAD

**Issue by blackxfiied** [chadmed/asahi-audio#8]
I have no idea how and am stuck

**Comment by chadmed** [comment]
Can't really offer general desktop support here, check whatever Ubuntu specific documentation exists. On KDE you just do it from the audio settings.

**Comment by blackxfiied** [comment]
i mean for kde, i tried going to pulseaudio settings but the only option other than [off] was [n/a (unplugged)]
