### ISSUE TITLE
How to remove asahi audio and start again?

### ISSUE THREAD

**Issue by blackxfiied** [chadmed/asahi-audio#9]
I installed asahi-audio without putting the built-in audio device into the pro-audio profile (whatever that means) and my dummy output device has disappeared and there are no more devices in my ubuntu

**Comment by chadmed** [comment]
Remove the folder `/usr/share/pipewire/devices/` and `/etc/pipewire/pipewire.conf.d/10-{machine}-sink.conf` then log out and log back in.
